version: "2.1"

services:
  wiki:
    build:
      context: .
    ports:
      - 5000:5000
    command: "api/main.py"
    volumes:
      - ./:/app
    env_file:
      - ./api/.env
    restart: unless-stopped
  ui:
    build:
      context: ./front-end
    ports:
      - 8080:8080
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: front-end
    volumes:
      - ./front-end:/usr/src/app/app
      - ./front-end/node_modules:/usr/src/app/app/node_modules
