version: "2.1"

services:
  wiki:
    build:
      context: .
    ports:
      - 9001:9001
    command: "src/main.py"
    volumes:
      - ./:/app
    restart: unless-stopped
  ui:
    build:
      context: ./markdown-ui
    ports:
      - 8080:8080
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: ui
    volumes:
      - ./markdown-ui:/usr/src/app/app
      - ./markdown-ui/node_modules:/usr/src/app/app/node_modules
