version: '2.6'                                                                                         
 
tasks:
  default:
    cmds:
      - docker-compose up --build
  install:
    cmds:
      - docker-compose run ui yarn install
  cypress:
    cmds:
      - docker-compose run ui yarn run cypress open
  test:
    cmds:
      - docker-compose run ui yarn test
  ci:
    cmds:
      - docker-compose run -u root ui yarn ci
  dev:
    cmds:
      - docker-compose up
