version: '2.6'                                                                                         
 
tasks:
  default:
    cmds:
      - docker-compose up --build
  dev:
    cmds:
      - docker-compose up
  ui_dev:
    cmds:
      - docker-compose run --service-ports --rm ui test-server
  ui_install:
    cmds:
      - docker-compose run --rm ui install
  cypress:
    cmds:
      - docker-compose run ui run --rm --service-ports cypress open
  cli_test:
    cmds:
      - docker-compose run --rm ui test
  ci:
    cmds:
      - docker-compose run -u root --rm ui ci
  fix_scrot_confilct:
    cmds:
      - git checkout --theirs front-end/cypress/
      - git add front-end/cypress/
  update_scrots:
    cmds:
      - echo "$(tput setaf 1)$(tput setab 7)Updating scrots! copy the following into your commit message and give a reason for update$(tput sgr 0)"
      - echo "------------------------"
      - find front-end/cypress/integration/__image_snapshots__ | grep actual | tr '\n' '\0' | xargs -0 -n1 rename -v '.actual' ''
      - find front-end/cypress/integration/__image_snapshots__ | grep diff | tr '\n' '\0' | xargs -0 -t -n1 rm
