version: '2.6'                                                                                         
 
tasks:
  default:
    cmds:
      - docker-compose up --build
  dev:
    cmds:
      - docker-compose up
  ui_dev:
    cmds:
      - docker-compose run ui test-server
  ui_install:
    cmds:
      - docker-compose run ui install
  cypress:
    cmds:
      - docker-compose run ui run cypress open
  cli_test:
    cmds:
      - docker-compose run ui test
  ci:
    cmds:
      - docker-compose run -u root ui ci
