version: '2.6'                                                                                         
 
tasks:
  default:
    description: run the wiki server
    cmds:
      - docker-compose up --build
