name: Static Analysis

on:
  pull_request:
  workflow_dispatch:

jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: install
        working-directory: ./front-end
        run: yarn install

      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-check
          eslint_flags: 'src/'
          workdir: ./front-end

  misspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run misspell
        uses: reviewdog/action-misspell@v1.9.0
